#!/bin/bash

# https://mywiki.wooledge.org/BashFAQ/028
if [[ $BASH_SOURCE = */* ]]; then
  cd -- "${BASH_SOURCE%/*}/" || exit 1
fi

dummy_stocks=(
  MU
  CL
  MSCI
  HPE
  DRI
  CVNA
  AAWW
  BECN
  CLBK
)

prog="$0"
usage() {
  printf 'usage: %s [-h] [--headless] [ticker_symbol ...]\n' "$prog" >&2
}
funds=()
while (( $# )); do
  case $1 in
    -h|--help)
      usage
      exit
      ;;
    --)
      shift
      break
      ;;
    -?*)
      usage
      printf '%s: error: unknown option %s\n' "$prog" "$1" >&2
      exit 1
      ;;
    *)
      funds+=("$1")
      ;;
  esac
  shift
done
options=()
while (( $# )); do
  case $1 in
    --)
      shift
      funds+=("$@")
      break
      ;;
    -?*)
      options+=("$1")
      ;;
    *)
      funds+=("$1")
      ;;
  esac
  shift
done

args=()
args+=("${options[@]}")
args+=(--)
args+=("${dummy_stocks[@]}")
if (( ${#funds[@]} < 1 )); then
  args+=(/dev/null)
else
  args+=(funds/"$(date +%Y%m%d)-funds.csv")
fi
args+=("${funds[@]}")
echo "${args[@]}"
source env/bin/activate
python3 morningstar.py "${args[@]}"
