#!/bin/bash

# https://mywiki.wooledge.org/BashFAQ/028
if [[ $BASH_SOURCE = */* ]]; then
  cd -- "${BASH_SOURCE%/*}/" || exit 1
fi

dummy_stocks=(
  MU
  CL
  MSCI
  HPE
  DRI
  CVNA
  AAWW
  BECN
  CLBK
)

prog="$0"
usage() {
  printf 'usage: %s [-h] [--debug] -- [--headless] -- [funds ...]\n' "$prog" >&2
}
debug=0
funds=()
while (( $# )); do
  case $1 in
    -h|--help)
      usage
      exit
      ;;
    --debug)
      debug=1
      ;;
    --)
      shift
      break
      ;;
    -?*)
      usage
      printf '%s: error: unknown option %s\n' "$prog" "$1" >&2
      exit 1
      ;;
    *)
      funds+=("$1")
      ;;
  esac
  shift
done
options=()
while (( $# )); do
  case $1 in
    --)
      shift
      funds+=("$@")
      break
      ;;
    -?*)
      options+=("$1")
      ;;
    *)
      funds+=("$1")
      ;;
  esac
  shift
done

args=()
if (( debug )); then
  args+=(python3 -m pdb morningstar.py)
else
  args+=(python3 morningstar.py)
fi
args+=("${options[@]}")
args+=(--)
args+=("${dummy_stocks[@]}")
if (( ${#funds[@]} < 1 )); then
  args+=(/dev/null)
else
  args+=(funds/"$(date +%Y%m%d)-funds.csv")
fi
args+=("${funds[@]}")
args_s=
start=1
for arg in "${args[@]}"; do
  if (( ! $start )); then
    args_s+=' '
  fi
  args_s+="$(printf -- '%q\n' "$arg")"
  start=0
done
printf -- '%s\n' "$args_s"
source env/bin/activate
"${args[@]}"
